#define MSG_000 wxT( "  Module IO Configurator" )
//#define MSG_001 wxT( "" )
//#define MSG_002 wxT( "" )
//#define MSG_003 wxT( "" )
//#define MSG_004 wxT( "" )
//#define MSG_005 wxT( "" )
//#define MSG_006 wxT( "" )
//#define MSG_007 wxT( "" )
//#define MSG_008 wxT( "" )
//#define MSG_009 wxT( "" )

//#define MSG_010 wxT( "" )
//#define MSG_011 wxT( "" )
//#define MSG_012 wxT( "" )
//#define MSG_013 wxT( "" )
//#define MSG_014 wxT( "" )
//#define MSG_015 wxT( "" )
//#define MSG_016 wxT( "" )
//#define MSG_017 wxT( "" )
//#define MSG_018 wxT( "" )
//#define MSG_019 wxT( "" )

//#define MSG_020 wxT( "" )
//#define MSG_021 wxT( "" )
//#define MSG_022 wxT( "" )
//#define MSG_023 wxT( "" )
//#define MSG_024 wxT( "" )
//#define MSG_025 wxT( "" )
//#define MSG_026 wxT( "" )
//#define MSG_027 wxT( "" )
//#define MSG_028 wxT( "" )
//#define MSG_029 wxT( "" )

//#define MSG_030 wxT( "" )
//#define MSG_031 wxT( "" )
//#define MSG_032 wxT( "" )
//#define MSG_033 wxT( "" )
//#define MSG_034 wxT( "" )
//#define MSG_035 wxT( "" )
//#define MSG_036 wxT( "" )
//#define MSG_037 wxT( "" )
//#define MSG_038 wxT( "" )
//#define MSG_039 wxT( "" )

//#define MSG_040 wxT( "" )
//#define MSG_041 wxT( "" )
//#define MSG_042 wxT( "" )
//#define MSG_043 wxT( "" )
//#define MSG_044 wxT( "" )
//#define MSG_045 wxT( "" )
//#define MSG_046 wxT( "" )
//#define MSG_047 wxT( "" )
//#define MSG_048 wxT( "" )
//#define MSG_049 wxT( "" )

//#define MSG_050 wxT( "" )
//#define MSG_051 wxT( "" )
//#define MSG_052 wxT( "" )
//#define MSG_053 wxT( "" )
//#define MSG_054 wxT( "" )
//#define MSG_055 wxT( "" )
//#define MSG_056 wxT( "" )
//#define MSG_057 wxT( "" )
//#define MSG_058 wxT( "" )
//#define MSG_059 wxT( "" )

//#define MSG_0 wxT( "" )
//#define MSG_1 wxT( "" )
//#define MSG_2 wxT( "" )
//#define MSG_3 wxT( "" )
//#define MSG_4 wxT( "" )
//#define MSG_5 wxT( "" )
//#define MSG_6 wxT( "" )
//#define MSG_7 wxT( "" )
//#define MSG_8 wxT( "" )
//#define MSG_9 wxT( "" )
               